# Site/SEO settings
email: pete.ruixi@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Ruixi Li
title: Ruixi "Peter" Li
description: >
  Hi, welcome to my page. My name is Ruixi Li, my friends call me Peter or Pete. 
  Learn more about me by exploring the site. 
  Hope you could get a good idea of who I am in the end. Thank you! 
url: http://peteruixi.netlify.com
#twitter_username: thomasvaeth
#default_img: /assets/images/seo.jpg
social:
  #- name: twitter
  #  url: https://twitter.com/thomasvaeth
  - name: instagram
    url: https://www.instagram.com/petaardation/
  - name: linkedin
    url: https://www.linkedin.com/in/ruixili/
  - name: github
    url: https://github.com/peteruixi
  #- name: codepen
  #  url: https://codepen.io/thomasvaeth/

# Contact settings
contact_img: /assets/images/placeholder-32.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Ruixi "Peter" Li
    bio: Ruixi Li was borned in China, received higher education in the United States. Currently in application for Masters.
    url: http://peteruixi.netlify.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Ruixi "Peter" Li'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
